### ISSUE TITLE
Re-design based on excisting concept

### ISSUE THREAD

**Issue by rodymol123** [isohuntto/openbay#91]
I have installed openbay on my localhost and have been working on another theme for it.
This is what i have so far (WIP):
![prev_tts](https://cloud.githubusercontent.com/assets/2954411/5562838/ada3f00a-8e3f-11e4-8dd7-c32ac7425231.png)

It is fully functional and easy to use.
If i get it done, i'll post it online.
Credit to Vitali Zakharoff for the concept.

**Comment by nasal** [comment]
Hi, I played a little with the screenshot you posted and created a theme. This is how it would look like: http://opb.rudikovac.com/ (only header and footer). 

Search results are not working because the remote Sphinx server is unavailable. Also, implementing a result view like this would take quite a bit of php coding as well.

If you have the time you could prepare another sub-page like Top 100 or a category list and I will try to add it.

If anybody is interested I can create a repo with the theme.

**Comment by benbristow** [comment]
That is absolutely gorgeous. Fantastic work! 

The only things now that I can recommend is that the cassette tape logo background should be made transparent since it's a different shade of black.

Also it would be nice to see the design made more responsive.

For someone who thinks he's not a great designer; you're darn good!

**Comment by TheChiefCoC** [comment]
Thats great guys, waiting for the release :D i can make a theme too but too lazy atm :/

**Comment by nasal** [comment]
I created a repo [here](https://github.com/nasal/newpiratebay).

**Comment by isdampe** [comment]
Great job nasal,

If I have some spare time I'll send some pull requests. It'd be good to get some SASS / build controls (Grunt?) happening too.

**Comment by rodymol123** [comment]
Great to see that you guys picked this up so quickly. ;) I won't be working on a OpenBay project anytime soon though. Keep it up!
